/**
 * Canonical Baseline State generated from Variable_Dictionary.md
 * ADR-002 through ADR-008 baselines are locked; empirical unknowns are UNKNOWN.
 */

export const CANONICAL_BASELINE = Object.freeze({
  "free_plan_enabled": true,
  "pro_tier_location_cap": 3,
  "business_tier_location_cap": 50,
  "trial_duration_days": 30,
  "trial_activation_trigger": "EXPLICIT",
  "free_history_retention_mode": "ROLLING_3_MONTH_WINDOW",
  "free_recommendation_gating_mode": "TOP_3_ANY_CATEGORY",
  "pro_price_monthly": 49000,
  "business_price_monthly": 149000,
  "visitor_count": "UNKNOWN",
  "signup_rate": "UNKNOWN",
  "signup_count": "UNKNOWN",
  "onboarding_completion_rate": "UNKNOWN",
  "onboarded_user_count": "UNKNOWN",
  "trial_start_rate": "UNKNOWN",
  "trial_user_count": "UNKNOWN",
  "trial_to_paid_conversion_rate": "UNKNOWN",
  "leads": "UNKNOWN",
  "qualified_leads": "UNKNOWN",
  "sales_conversion_rate": "UNKNOWN",
  "referral_rate": "UNKNOWN",
  "marketing_spend": "UNKNOWN",
  "cac": "UNKNOWN",
  "monthly_account_churn_rate": "UNKNOWN",
  "churned_customer_count": "UNKNOWN",
  "retained_customer_count": "UNKNOWN",
  "active_free_customers": "UNKNOWN",
  "active_pro_customers": "UNKNOWN",
  "active_business_customers": "UNKNOWN",
  "total_paid_customers": "UNKNOWN",
  "new_paid_customer_count": "UNKNOWN",
  "pro_mrr": "UNKNOWN",
  "business_mrr": "UNKNOWN",
  "total_mrr": "UNKNOWN",
  "arr": "UNKNOWN",
  "arpu": "UNKNOWN",
  "arpa": "UNKNOWN",
  "arpa_per_location": "UNKNOWN",
  "average_locations_per_business_account": "UNKNOWN",
  "support_tickets_per_customer": "UNKNOWN",
  "support_tickets_per_location": "UNKNOWN",
  "support_capacity": "UNKNOWN",
  "support_burden": "UNKNOWN",
  "support_cost_per_ticket": "UNKNOWN",
  "monthly_support_cost": "UNKNOWN",
  "hosting_cost": "UNKNOWN",
  "database_cost": "UNKNOWN",
  "inference_cost": 0,
  "payment_gateway_cost": 0,
  "customer_support_cost": "UNKNOWN",
  "marketing_cost": "UNKNOWN",
  "monthly_operating_cost": "UNKNOWN",
  "gross_profit": "UNKNOWN",
  "gross_margin_rate": "UNKNOWN",
  "monthly_burn": "UNKNOWN",
  "cash_balance": "UNKNOWN",
  "cash_runway_months": "UNKNOWN",
  "revenue_after_electricity": "UNKNOWN",
  "data_provenance_mode": "STRICT_TAGGED",
  "recorded_meter_data_ratio": "UNKNOWN",
  "estimated_value_ratio": "UNKNOWN",
  "data_completeness_score": "UNKNOWN",
  "data_quality_score": "UNKNOWN",
  "forecast_method": "DETERMINISTIC_HEURISTIC",
  "forecast_error_rate": "UNKNOWN",
  "forecast_confidence": "UNKNOWN",
  "forecast_compute_cost": 0
});

export default CANONICAL_BASELINE;
