/**
 * Canonical 67-Variable Catalog generated from Variable_Dictionary.md
 */

export const VARIABLES = Object.freeze([
  {
    "id": "free_plan_enabled",
    "name": "Free Plan Availability",
    "domain": "PRODUCT",
    "description": "Controls whether the zero-cost Free tier is accessible for customer acquisition.",
    "role": "CONTROL",
    "dataType": "boolean",
    "unit": "`boolean`",
    "knowledgeStatus": "CURRENT",
    "baselineValue": true,
    "allowedValues": [
      true,
      false
    ],
    "minimum": null,
    "maximum": null,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Configured in prototype Plans/Index.vue)",
    "notes": "Disabling this lever models a paid-only product acquisition model."
  },
  {
    "id": "pro_tier_location_cap",
    "name": "Pro Plan Location Entitlement Cap",
    "domain": "PRODUCT",
    "description": "Maximum number of active commercial locations an account on the Pro tier is permitted to manage.",
    "role": "CONTROL",
    "dataType": "integer",
    "unit": "`locations/account`",
    "knowledgeStatus": "CURRENT & ACCEPTED_BASELINE",
    "baselineValue": 3,
    "allowedValues": [
      1,
      3
    ],
    "minimum": 1,
    "maximum": 3,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Backend code configures 3; frontend UI copy displays single-location messaging, documented as implementation gap).",
    "notes": "Cannibalization of Business tier is tested as a dynamic simulation hypothesis, not an empirical given."
  },
  {
    "id": "business_tier_location_cap",
    "name": "Business Plan Location Entitlement Cap",
    "domain": "PRODUCT",
    "description": "Maximum number of active commercial branch locations an account on the Business tier is permitted to manage.",
    "role": "CONTROL",
    "dataType": "integer",
    "unit": "`locations/account`",
    "knowledgeStatus": "ACCEPTED_BASELINE",
    "baselineValue": 50,
    "allowedValues": [
      5,
      10,
      50
    ],
    "minimum": 1,
    "maximum": 50,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "PROTOTYPE_GAP (Backend configures 50; marketing UI displays 5; PRD §14 specifies 10).",
    "notes": "Simulator models the operational stress, database bloat, and margin dilution of 50 locations versus 5 or 10."
  },
  {
    "id": "trial_duration_days",
    "name": "Pro Trial Duration",
    "domain": "PRODUCT",
    "description": "Duration in calendar days of the full-featured Pro tier evaluation granted to eligible users.",
    "role": "CONSTANT",
    "dataType": "integer",
    "unit": "`days`",
    "knowledgeStatus": "CURRENT & ACCEPTED_BASELINE",
    "baselineValue": 30,
    "allowedValues": [
      14,
      30
    ],
    "minimum": 7,
    "maximum": 60,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Hardcoded 30 days in PlanController::startTrial).",
    "notes": "Stable reference constant governing the evaluation cohort maturity window."
  },
  {
    "id": "trial_activation_trigger",
    "name": "Pro Trial Activation Trigger Mechanism",
    "domain": "PRODUCT",
    "description": "Determines whether a 30-day Pro trial activates automatically upon onboarding completion or requires explicit user opt-in action.",
    "role": "CONTROL",
    "dataType": "enum",
    "unit": "`enum`",
    "knowledgeStatus": "CURRENT & ACCEPTED_BASELINE",
    "baselineValue": "EXPLICIT",
    "allowedValues": [
      "EXPLICIT",
      "AUTOMATIC"
    ],
    "minimum": null,
    "maximum": null,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Snapshot code requires explicit activation; automatic trial preserved as growth scenario).",
    "notes": "`EXPLICIT` yields higher intent cohorts; `AUTOMATIC` produces larger cohort volume with lower conversion intent."
  },
  {
    "id": "free_history_retention_mode",
    "name": "Free Tier Historical Data Retention Mode",
    "domain": "PRODUCT",
    "description": "Data retention policy governing historical billing entry access for Free tier accounts.",
    "role": "CONTROL",
    "dataType": "enum",
    "unit": "`enum`",
    "knowledgeStatus": "ACCEPTED_BASELINE / TARGET",
    "baselineValue": "ROLLING_3_MONTH_WINDOW",
    "allowedValues": [
      "ROLLING_3_MONTH_WINDOW",
      "HARD_3_ENTRY_LIFETIME_CAP"
    ],
    "minimum": null,
    "maximum": null,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "PROTOTYPE_GAP (Current prototype snapshot code enforces count >= 3 lifetime cap; rolling 3-month window is canonical target baseline).",
    "notes": "Prototype implementation gap documented; lifetime cap preserved as paywall friction stress test."
  },
  {
    "id": "free_recommendation_gating_mode",
    "name": "Free Tier Recommendation Gating Mode",
    "domain": "PRODUCT",
    "description": "Governs which energy-saving inspection recommendations are unblurred and visible to accounts on the Free plan.",
    "role": "CONTROL",
    "dataType": "enum",
    "unit": "`enum`",
    "knowledgeStatus": "CURRENT & SIMULATION",
    "baselineValue": "TOP_3_ANY_CATEGORY",
    "allowedValues": [
      "TOP_3_ANY_CATEGORY",
      "DATA_COMPLETENESS_ALERTS_ONLY"
    ],
    "minimum": null,
    "maximum": null,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Prototype implements TOP_3_ANY_CATEGORY; DATA_COMPLETENESS_ALERTS_ONLY is PRD alternative).",
    "notes": "Tests value exposure against upgrade urgency."
  },
  {
    "id": "pro_price_monthly",
    "name": "Pro Plan Monthly Subscription Price",
    "domain": "PRICING",
    "description": "Flat monthly subscription fee charged for a Pro plan account.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "CURRENT (UI Display) / HYPOTHESIS (WTP)",
    "baselineValue": 49000,
    "allowedValues": [
      29000,
      49000,
      79000
    ],
    "minimum": 10000,
    "maximum": 200000,
    "confidence": "`HIGH` (as displayed pilot price) / `UNKNOWN` (as market equilibrium)",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (UI copy displays Rp49.000; payment gateway not yet live).",
    "notes": "Intended to trigger impulsive conversion below 1 room's single daily electricity waste."
  },
  {
    "id": "business_price_monthly",
    "name": "Business Plan Monthly Subscription Price",
    "domain": "PRICING",
    "description": "Flat monthly subscription fee charged for a multi-location Business plan account.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "CURRENT (UI Display) / HYPOTHESIS (WTP)",
    "baselineValue": 149000,
    "allowedValues": [
      99000,
      149000,
      249000
    ],
    "minimum": 50000,
    "maximum": 1000000,
    "confidence": "`HIGH` (as displayed pilot price) / `UNKNOWN` (as market equilibrium)",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (UI copy displays Rp149.000; payment gateway not yet live).",
    "notes": "Flat fee introduces margin dilution as branch count scales toward 50."
  },
  {
    "id": "visitor_count",
    "name": "Monthly Unique Web Visitors",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Total unique prospective commercial users visiting the landing page or portal per month.",
    "role": "INPUT",
    "dataType": "integer",
    "unit": "`visitors/month`",
    "knowledgeStatus": "UNKNOWN / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      200,
      1000,
      5000
    ],
    "minimum": 0,
    "maximum": 100000,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Top-of-pipe traffic volume. No verified production web analytics logged."
  },
  {
    "id": "signup_rate",
    "name": "Visitor to Signup Conversion Rate",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Ratio of unique site visitors who initiate account registration.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "HYPOTHESIS / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0.02,
      0.05,
      0.1
    ],
    "minimum": 0.001,
    "maximum": 0.3,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Assumes frictionless registration via credentials."
  },
  {
    "id": "signup_count",
    "name": "Monthly New Signups",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Aggregate number of user accounts registered in a simulation month.",
    "role": "DERIVED",
    "dataType": "integer",
    "unit": "`users/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 50000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Intermediate funnel state."
  },
  {
    "id": "onboarding_completion_rate",
    "name": "Onboarding Completion Rate",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Proportion of registered signups who complete business profile setup and enter their first electricity bill.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "SOURCE_BACKED_TARGET / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      "0.30 (Conservative)",
      "0.50 (Pilot Baseline)",
      "0.60 (PRD §15 Target)",
      "0.85 (Optimistic Target)"
    ],
    "minimum": 0.1,
    "maximum": 0.95,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Values 0.50, 0.60, 0.85 are source-backed targets from PRD §15 and Brief S00, not realized customer conversion. Major drop-off expected if manual meter entry friction is high."
  },
  {
    "id": "onboarded_user_count",
    "name": "Monthly Onboarded Users",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Count of users completing profile setup and initial utility baseline entry per month.",
    "role": "DERIVED",
    "dataType": "integer",
    "unit": "`users/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 50000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Qualified activated user base."
  },
  {
    "id": "trial_start_rate",
    "name": "Trial Initiation Rate",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Ratio of onboarded users who enter the 30-day Pro trial.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0.1,
      0.25,
      0.5,
      1
    ],
    "minimum": 0.05,
    "maximum": 1,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. 1.00 represents theoretical automatic trial trigger scenario; 0.25 is an unvalidated illustrative hypothesis. Governed directly by `trial_activation_trigger` policy."
  },
  {
    "id": "trial_user_count",
    "name": "Active Trial Cohort Size",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Number of users currently undergoing an active 30-day Pro evaluation.",
    "role": "STATE",
    "dataType": "integer",
    "unit": "`users`",
    "knowledgeStatus": "STATE_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 25000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "State variable representing mature cohort awaiting conversion decision."
  },
  {
    "id": "trial_to_paid_conversion_rate",
    "name": "Trial-to-Paid Conversion Rate",
    "domain": "CUSTOMER_JOURNEY",
    "description": "Proportion of trial users completing their 30-day evaluation who transition into paying subscribers.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "SOURCE_BACKED_TARGET / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      "0.01 (Pessimistic)",
      "0.02 (Conservative)",
      "0.03 (PRD §15 Target)",
      "0.05 (Optimistic Target)",
      "0.10 (Brief S00 Stretch)"
    ],
    "minimum": 0.005,
    "maximum": 0.25,
    "confidence": "`LOW` (Zero verified paid transactions in snapshot)",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Primary monetization hurdle. Zero verified paid transactions in snapshot (SRC-022 missing). 0.03 and 0.10 are unvalidated aspirational targets. Sensitive to perceived forecasting utility and trial intent."
  },
  {
    "id": "leads",
    "name": "Monthly Inbound & Outreach Leads",
    "domain": "GROWTH",
    "description": "Raw volume of commercial business leads contacted through direct outreach, partner associations, and digital campaigns.",
    "role": "INPUT",
    "dataType": "integer",
    "unit": "`leads/month`",
    "knowledgeStatus": "SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      20,
      100,
      500
    ],
    "minimum": 0,
    "maximum": 10000,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Unvalidated direct outreach channel."
  },
  {
    "id": "qualified_leads",
    "name": "Marketing/Sales Qualified Leads (MQL)",
    "domain": "GROWTH",
    "description": "Leads meeting the Ideal Customer Profile (ICP) criteria (commercial SME, electricity spend > Rp2.000.000/month).",
    "role": "DERIVED",
    "dataType": "integer",
    "unit": "`leads/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 5000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Assumes commercial electricity profile filter."
  },
  {
    "id": "sales_conversion_rate",
    "name": "Direct Sales Conversion Rate",
    "domain": "GROWTH",
    "description": "Success rate of founder-led or direct sales outreach in converting qualified leads directly to paid or high-intent pilot status.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "HYPOTHESIS / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0.05,
      0.15,
      0.3
    ],
    "minimum": 0.01,
    "maximum": 0.5,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Reflects founder-led sales efficiency during early pilot phase."
  },
  {
    "id": "referral_rate",
    "name": "Monthly Customer Referral Rate",
    "domain": "GROWTH",
    "description": "Percentage of existing active customer accounts that successfully introduce a new registered customer each month.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "HYPOTHESIS / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0,
      0.02,
      0.05
    ],
    "minimum": 0,
    "maximum": 0.2,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Organic word-of-mouth multiplier driven by product usefulness."
  },
  {
    "id": "marketing_spend",
    "name": "Monthly Marketing & Acquisition Spend",
    "domain": "GTM",
    "description": "Total monthly discretionary budget allocated to digital marketing, search/social ads, and founder sales outreach.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0,
      2000000,
      10000000
    ],
    "minimum": 0,
    "maximum": 50000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Primary growth lever in venture scaling scenarios. Level 3 missing marketing ledger (`SRC-021`)."
  },
  {
    "id": "cac",
    "name": "Customer Acquisition Cost (Blended CAC)",
    "domain": "GTM",
    "description": "Fully loaded sales and marketing expense required to secure one new paying subscriber.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/paid_customer`",
    "knowledgeStatus": "UNKNOWN / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 5000000,
    "confidence": "`UNKNOWN`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Level 3 missing financial truth. Critical parameter for venture viability testing."
  },
  {
    "id": "monthly_account_churn_rate",
    "name": "Monthly Account Churn Rate",
    "domain": "RETENTION",
    "description": "Percentage of active paid customer accounts cancelling, terminating, or failing to renew their subscription in a given month.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`ratio/month`",
    "knowledgeStatus": "SOURCE_BACKED_TARGET / SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      "0.03 (Best-in-Class SaaS)",
      "0.05 (Brief S00 Target)",
      "0.08 (Moderate Commercial Churn)",
      "0.15 (Stress Test)"
    ],
    "minimum": 0.01,
    "maximum": 0.4,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** `empirical_validation_required = YES`. Inversely determines customer lifetime ($1/\\text{churn}$). Zero empirical customer lifecycle data in snapshot (`SRC-022` missing). 0.05 is an assumption from Brief S00; 0.15 is a synthetic stress test."
  },
  {
    "id": "churned_customer_count",
    "name": "Monthly Churned Accounts",
    "domain": "RETENTION",
    "description": "Total paid subscriber accounts lost during the current simulation month.",
    "role": "DERIVED",
    "dataType": "integer",
    "unit": "`customers/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 10000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Deducted from paid subscriber base."
  },
  {
    "id": "retained_customer_count",
    "name": "Monthly Retained Accounts",
    "domain": "RETENTION",
    "description": "Total paid subscriber accounts continuing active paid status from previous month.",
    "role": "DERIVED",
    "dataType": "integer",
    "unit": "`customers/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 50000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Base for ongoing MRR."
  },
  {
    "id": "active_free_customers",
    "name": "Active Free Tier Accounts",
    "domain": "REVENUE",
    "description": "Total active accounts currently utilizing the Free tier without paying subscription fees.",
    "role": "STATE",
    "dataType": "integer",
    "unit": "`customers`",
    "knowledgeStatus": "STATE_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 100000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Incurs database storage cost while acting as an upgrade pipeline."
  },
  {
    "id": "active_pro_customers",
    "name": "Active Pro Plan Subscribers",
    "domain": "REVENUE",
    "description": "Number of paying accounts currently subscribed to the Pro plan.",
    "role": "STATE",
    "dataType": "integer",
    "unit": "`customers`",
    "knowledgeStatus": "STATE_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 50000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Primary driver of initial recurring revenue."
  },
  {
    "id": "active_business_customers",
    "name": "Active Business Plan Subscribers",
    "domain": "REVENUE",
    "description": "Number of multi-location commercial accounts currently subscribed to the Business plan.",
    "role": "STATE",
    "dataType": "integer",
    "unit": "`customers`",
    "knowledgeStatus": "STATE_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 10000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "High ARPA account class with significant operational footprint."
  },
  {
    "id": "total_paid_customers",
    "name": "Total Paid Subscribers",
    "domain": "REVENUE",
    "description": "Aggregate active paying accounts (`active_pro_customers + active_business_customers`).",
    "role": "STATE",
    "dataType": "integer",
    "unit": "`customers`",
    "knowledgeStatus": "STATE_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 60000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** Core operational milestone metric."
  },
  {
    "id": "new_paid_customer_count",
    "name": "Monthly New Paid Customers",
    "domain": "REVENUE",
    "description": "Total newly converted paying customers joining in the simulation month across self-serve trials and direct sales.",
    "role": "DERIVED",
    "dataType": "integer",
    "unit": "`customers/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 10000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Driver of monthly MRR growth."
  },
  {
    "id": "pro_mrr",
    "name": "Pro Tier Monthly Recurring Revenue",
    "domain": "REVENUE",
    "description": "Total recurring revenue generated from active Pro subscriptions in a month.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 5000000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Pro tier recurring revenue stream."
  },
  {
    "id": "business_mrr",
    "name": "Business Tier Monthly Recurring Revenue",
    "domain": "REVENUE",
    "description": "Total recurring revenue generated from active Business subscriptions in a month.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 5000000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Commercial portfolio subscription revenue."
  },
  {
    "id": "total_mrr",
    "name": "Total Monthly Recurring Revenue (MRR)",
    "domain": "REVENUE",
    "description": "Aggregate monthly recurring subscription revenue (`pro_mrr + business_mrr`).",
    "role": "OUTPUT",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 10000000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** Key top-line business metric."
  },
  {
    "id": "arr",
    "name": "Annual Run-Rate Revenue (ARR)",
    "domain": "REVENUE",
    "description": "Annualized revenue run-rate calculated as `total_mrr * 12`.",
    "role": "OUTPUT",
    "dataType": "float",
    "unit": "`IDR/year`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 120000000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Annualization identity for investor milestone tracking."
  },
  {
    "id": "arpu",
    "name": "Average Revenue Per User (Blended ARPU)",
    "domain": "REVENUE",
    "description": "Average monthly revenue across all registered active customer accounts (`total_mrr / (active_free + total_paid)`).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/customer/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 500000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Diluted by Free tier user volume."
  },
  {
    "id": "arpa",
    "name": "Average Revenue Per Account (Paid ARPA)",
    "domain": "REVENUE",
    "description": "Average monthly subscription revenue generated exclusively per paying account (`total_mrr / total_paid_customers`).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/paid_customer/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 29000,
    "maximum": 249000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Weighted mix of Pro vs Business accounts."
  },
  {
    "id": "arpa_per_location",
    "name": "Effective ARPA Per Managed Location",
    "domain": "REVENUE",
    "description": "Normalized monthly revenue earned per managed business branch (`business_mrr / (active_business_customers * average_locations_per_business_account)`).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/location/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 1000,
    "maximum": 149000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Key variable for measuring unit economic dilution under multi-site expansion (C-003)."
  },
  {
    "id": "average_locations_per_business_account",
    "name": "Average Locations Per Business Account",
    "domain": "OPERATIONS",
    "description": "Mean number of active physical branches or meter locations managed by a single Business subscriber.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`locations/account`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scenarios)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      1,
      5,
      8,
      25,
      50
    ],
    "minimum": 1,
    "maximum": 50,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Constrained by `business_tier_location_cap` (50). Zero empirical commercial multi-site accounts live in snapshot."
  },
  {
    "id": "support_tickets_per_customer",
    "name": "Base Support Ticket Rate Per Account",
    "domain": "OPERATIONS",
    "description": "Baseline monthly customer support tickets, onboarding inquiries, and billing assistance requests generated per customer account.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`tickets/customer/month`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scenarios)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0.05,
      0.2,
      0.8
    ],
    "minimum": 0.01,
    "maximum": 3,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not actual WattWise historical data. Represents uncalibrated simulation assumption."
  },
  {
    "id": "support_tickets_per_location",
    "name": "Incremental Support Ticket Rate Per Branch Location",
    "domain": "OPERATIONS",
    "description": "Additional monthly operational support tickets created for each supplementary location managed by a multi-site Business account.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`tickets/location/month`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scenarios)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0.02,
      0.1,
      0.3
    ],
    "minimum": 0,
    "maximum": 1.5,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not actual WattWise historical data. Drives non-linear support load on Business tier accounts with up to 50 locations."
  },
  {
    "id": "support_capacity",
    "name": "Monthly Support Resolution Capacity",
    "domain": "OPERATIONS",
    "description": "Maximum monthly ticket volume the existing team or founder can effectively handle without service degradation or external hiring.",
    "role": "CONSTANT",
    "dataType": "float",
    "unit": "`tickets/month`",
    "knowledgeStatus": "SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      50,
      100,
      300
    ],
    "minimum": 10,
    "maximum": 2000,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not actual WattWise team payroll log. Threshold above which support quality deteriorates, triggering churn feedback."
  },
  {
    "id": "support_burden",
    "name": "Support Burden Ratio",
    "domain": "SUPPORT",
    "description": "Operational stress index representing generated support ticket demand relative to available resolution capacity (`total_tickets / support_capacity`).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 10,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** Values > 1.0 indicate operational overload and trigger retention penalties."
  },
  {
    "id": "support_cost_per_ticket",
    "name": "Operational Cost Per Support Ticket",
    "domain": "SUPPORT",
    "description": "Blended labor, tool, and administrative expense incurred to resolve a single customer support inquiry.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`IDR/ticket`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scenarios)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      10000,
      25000,
      60000
    ],
    "minimum": 5000,
    "maximum": 150000,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not actual WattWise accounting data. In early phase, represents founder opportunity cost; later represents support payroll."
  },
  {
    "id": "monthly_support_cost",
    "name": "Total Monthly Customer Support Cost",
    "domain": "SUPPORT",
    "description": "Aggregate monthly financial outlay devoted to customer support and onboarding management.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 50000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Directly reduces gross margin when multi-site burden spikes."
  },
  {
    "id": "hosting_cost",
    "name": "Cloud Web & App Server Hosting Cost",
    "domain": "COST",
    "description": "Base monthly fixed infrastructure cost for web servers, frontend hosting (Vercel), and API runtime.",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "SIMULATION_ASSUMPTION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      150000,
      350000,
      1000000
    ],
    "minimum": 0,
    "maximum": 10000000,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not actual WattWise accounting data. Baseline Vercel Pro ($20/mo $\\approx$ Rp320.000) or VPS hosting."
  },
  {
    "id": "database_cost",
    "name": "Database Storage & Query Cost",
    "domain": "COST",
    "description": "Monthly database instance, storage, and I/O cost scaling with active customers, locations, and historical bill entries.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scaling curve)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      100000,
      500000,
      2000000
    ],
    "minimum": 100000,
    "maximum": 15000000,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not actual WattWise accounting invoice. Database cost grows with multi-location Business accounts and rolling free history."
  },
  {
    "id": "inference_cost",
    "name": "Cloud AI / Model Inference Cost",
    "domain": "COST",
    "description": "Monthly expenditure for cloud GPU/API execution for consumption prediction and recommendation ranking.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "CURRENT & ACCEPTED_BASELINE (Baseline = 0) / SIMULATION",
    "baselineValue": 0,
    "allowedValues": [
      0,
      500000,
      2500000
    ],
    "minimum": 0,
    "maximum": 20000000,
    "confidence": "`HIGH` (Deterministic heuristic runs locally in PHP with Rp0 external API cost)",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Baseline = 0; future ML models introduce GPU costs).",
    "notes": "Current code is pure PHP arithmetic; ML GPU costs are NOT CURRENT and modeled only in future scenarios."
  },
  {
    "id": "payment_gateway_cost",
    "name": "Payment Processing Fees",
    "domain": "COST",
    "description": "Monthly variable fees paid to financial transaction processors (e.g. Midtrans, Xendit).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "CURRENT (Baseline = 0) / SIMULATION",
    "baselineValue": 0,
    "allowedValues": null,
    "minimum": 0,
    "maximum": 100000000,
    "confidence": "`HIGH` (Zero automated payment processing currently live in snapshot)",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Rp0 in current snapshot; modeled as transaction fee when gateway enabled).",
    "notes": "COGS deduction directly affecting gross margin."
  },
  {
    "id": "customer_support_cost",
    "name": "Customer Support COGS",
    "domain": "COST",
    "description": "Customer support operational cost assigned as direct service expense.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 50000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Direct variable operational cost."
  },
  {
    "id": "marketing_cost",
    "name": "Monthly Sales & Marketing Expense",
    "domain": "COST",
    "description": "Operating cost for commercial growth and marketing campaigns (`marketing_spend`).",
    "role": "INPUT",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "SIMULATION_INPUT",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0,
      2000000,
      10000000
    ],
    "minimum": 0,
    "maximum": 50000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Operating expense (OpEx), excluded from COGS."
  },
  {
    "id": "monthly_operating_cost",
    "name": "Total Monthly Operating Cost (OpEx + COGS)",
    "domain": "COST",
    "description": "Aggregate monthly venture operational spend (`hosting_cost + database_cost + inference_cost + payment_gateway_cost + customer_support_cost + marketing_cost`).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 200000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Determines venture cash burn rate."
  },
  {
    "id": "gross_profit",
    "name": "Gross Contribution Profit",
    "domain": "FINANCE",
    "description": "Total MRR minus direct Cost of Goods Sold (`database_cost + inference_cost + payment_gateway_cost + customer_support_cost`).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": -50000000,
    "maximum": 10000000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Tests whether subscription pricing covers variable delivery load."
  },
  {
    "id": "gross_margin_rate",
    "name": "Gross Margin Rate",
    "domain": "FINANCE",
    "description": "Ratio of gross profit to total MRR (`gross_profit / total_mrr`).",
    "role": "OUTPUT",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": -2,
    "maximum": 1,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** Key indicator of subscription viability under multi-location stress."
  },
  {
    "id": "monthly_burn",
    "name": "Monthly Net Cash Burn",
    "domain": "FINANCE",
    "description": "Monthly net cash deficit (`monthly_operating_cost - total_mrr`). Negative value indicates cash generation.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/month`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": -5000000000,
    "maximum": 200000000,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "Net cash outflow rate eroding reserves."
  },
  {
    "id": "cash_balance",
    "name": "Venture Cash Reserves",
    "domain": "FINANCE",
    "description": "Liquid capital reserves available in the venture bank account to fund operations.",
    "role": "STATE",
    "dataType": "float",
    "unit": "`IDR`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scenarios)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      10000000,
      50000000,
      200000000
    ],
    "minimum": 0,
    "maximum": 10000000000,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not actual WattWise bank balance ledger. Core solvency reserve; reaching zero triggers venture insolvency."
  },
  {
    "id": "cash_runway_months",
    "name": "Cash Runway Duration",
    "domain": "FINANCE",
    "description": "Estimated months of operational solvency remaining before cash reserves deplete at current burn rate (`cash_balance / monthly_burn`).",
    "role": "OUTPUT",
    "dataType": "float",
    "unit": "`months`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 120,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** Survival countdown for venture defense."
  },
  {
    "id": "revenue_after_electricity",
    "name": "Revenue After Electricity Expense (\"Sisa Pendapatan Setelah Listrik\")",
    "domain": "FINANCE",
    "description": "Client-facing operational metric for commercial MSMEs: gross monthly revenue minus actual monthly electricity utility expense.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`IDR/business/month`",
    "knowledgeStatus": "ACCEPTED_CANONICAL_METRIC",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 1000000000,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (In RecommendationService.php).",
    "notes": "**CRITICAL ACCOUNTING DISTINCTION:** This represents micro-business electricity gross contribution. It must NOT be confused with venture gross profit, venture net income, or cash balance! \"Sisa Kas Bersih\" is permanently retired."
  },
  {
    "id": "data_provenance_mode",
    "name": "Data Ingestion Provenance Protocol",
    "domain": "DATA_QUALITY",
    "description": "Data ingestion mode dictating whether electricity entries are strictly tagged by provenance source (`RECORDED_METER` vs `ESTIMATED_VALUE`).",
    "role": "CONTROL",
    "dataType": "enum",
    "unit": "`enum`",
    "knowledgeStatus": "ACCEPTED_BASELINE",
    "baselineValue": "STRICT_TAGGED",
    "allowedValues": [
      "STRICT_TAGGED",
      "UNTAGGED_UNIFORM"
    ],
    "minimum": null,
    "maximum": null,
    "confidence": "`HIGH`",
    "editable": false,
    "implementationStatus": "PROTOTYPE_GAP (Current SaaS database lacks is_estimated flag in electricity_entries).",
    "notes": "`STRICT_TAGGED` is mandatory simulator baseline contract; `UNTAGGED_UNIFORM` is degradation stress-test."
  },
  {
    "id": "recorded_meter_data_ratio",
    "name": "Recorded Physical Meter Data Ratio",
    "domain": "DATA_QUALITY",
    "description": "Proportion of customer billing records supported by actual physical meter photographs or exact meter readings.",
    "role": "STATE",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scenarios)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0.2,
      0.8,
      1
    ],
    "minimum": 0,
    "maximum": 1,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Not empirical field data. Higher ratio increases forecast confidence."
  },
  {
    "id": "estimated_value_ratio",
    "name": "Synthetic / Estimated Data Ratio",
    "domain": "DATA_QUALITY",
    "description": "Proportion of customer billing records generated through algorithmic estimation (kWh $\\times$ tariff) without verified meter reading.",
    "role": "STATE",
    "dataType": "float",
    "unit": "`ratio`",
    "knowledgeStatus": "STATE_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0,
      0.2,
      0.8
    ],
    "minimum": 0,
    "maximum": 1,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "In untagged mode, estimated data quietly degrades downstream forecasting without user awareness."
  },
  {
    "id": "data_completeness_score",
    "name": "Monthly History Completeness Score",
    "domain": "DATA_QUALITY",
    "description": "Metric evaluating continuous sequential monthly billing records (0 to 12 months without gaps).",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`score (0-1)`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 1,
    "confidence": "`HIGH` (Logic verified in code: <3 months = no trend; $\\ge 3$ months = trend heuristic)",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "At least 3 contiguous months are required for trend slope in heuristic forecasting."
  },
  {
    "id": "data_quality_score",
    "name": "Composite Data Quality Index",
    "domain": "DATA_QUALITY",
    "description": "Holistic data integrity rating combining provenance tagging, completeness, and volatility variance.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`score (0-1)`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 1,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** Key driver of customer trust and habit retention."
  },
  {
    "id": "forecast_method",
    "name": "Electricity Consumption Forecasting Method",
    "domain": "FORECASTING",
    "description": "Underlying computational methodology used to forecast next-month electricity consumption.",
    "role": "CONTROL",
    "dataType": "enum",
    "unit": "`enum`",
    "knowledgeStatus": "CURRENT & ACCEPTED_BASELINE",
    "baselineValue": "DETERMINISTIC_HEURISTIC",
    "allowedValues": [
      "DETERMINISTIC_HEURISTIC",
      "GRADIENT_BOOSTING",
      "LSTM",
      "OTHER_ML"
    ],
    "minimum": null,
    "maximum": null,
    "confidence": "`HIGH` (Snapshot code verified 100% deterministic PHP math)",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (DETERMINISTIC_HEURISTIC is implemented in code; ML variants are NOT CURRENT and modeled only in future scenarios).",
    "notes": "Machine Learning is NOT CURRENT. No GPU costs modeled in baseline."
  },
  {
    "id": "forecast_error_rate",
    "name": "Forecast Mean Absolute Percentage Error (MAPE)",
    "domain": "FORECASTING",
    "description": "Average percentage divergence between forecasted monthly consumption and actual billed kWh.",
    "role": "STATE",
    "dataType": "float",
    "unit": "`ratio (MAPE)`",
    "knowledgeStatus": "UNKNOWN (Baseline) / SIMULATION_ASSUMPTION (Scenarios)",
    "baselineValue": "UNKNOWN",
    "allowedValues": [
      0.04,
      0.12,
      0.25
    ],
    "minimum": 0.01,
    "maximum": 0.8,
    "confidence": "`LOW`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "`empirical_validation_required = YES`. Neither 0.12 nor 0.07 is an empirical baseline or proven ML accuracy benchmark; uncalibrated forecasting accuracy in commercial field settings. Machine Learning remains `TARGET / FUTURE / SIMULATION`, not current production reality."
  },
  {
    "id": "forecast_confidence",
    "name": "Forecast Output Confidence Rating",
    "domain": "FORECASTING",
    "description": "Confidence band rating exposed to the user accompanying consumption projections.",
    "role": "DERIVED",
    "dataType": "float",
    "unit": "`score (0-1)`",
    "knowledgeStatus": "DERIVED_SIMULATION",
    "baselineValue": "UNKNOWN",
    "allowedValues": null,
    "minimum": 0,
    "maximum": 1,
    "confidence": "`MEDIUM`",
    "editable": false,
    "implementationStatus": "SIMULATOR_SPEC",
    "notes": "**Primary Output: YES.** Informs user whether the prediction is reliable."
  },
  {
    "id": "forecast_compute_cost",
    "name": "Compute Cost Per Forecast Generation",
    "domain": "FORECASTING",
    "description": "Computational expense incurred per forecast evaluation run.",
    "role": "CONSTANT",
    "dataType": "float",
    "unit": "`IDR/forecast`",
    "knowledgeStatus": "CURRENT & ACCEPTED_BASELINE (Baseline = 0) / SIMULATION",
    "baselineValue": 0,
    "allowedValues": [
      0,
      50,
      500
    ],
    "minimum": 0,
    "maximum": 5000,
    "confidence": "`HIGH` (Deterministic PHP arithmetic runs in existing thread at Rp0 variable compute)",
    "editable": false,
    "implementationStatus": "IMPLEMENTED (Rp0 in current baseline; simulation parameter for future cloud ML scenarios).",
    "notes": "Cloud ML models require paid API/GPU calls; heuristic requires none."
  }
]);

export default VARIABLES;
